### ISSUE TITLE
Clone for cache::Package

### ISSUE THREAD

**Issue by MggMuggins** [Morganamilo/raur-ext#1]
I have this implemented on my machine but it's pending on [raur#5](https://gitlab.com/davidbittner/raur/issues/5). I'll open a PR to here as soon as David releases 1.0.3.

**Comment by MggMuggins** [comment]
See #2

**Comment by MggMuggins** [comment]
#3 Resolves this issue

**Comment by Morganamilo** [comment]
Apparently I was not watching this repo. Even though that should be on by default whenever a new repo is crated.

However this was a problem for me too. Hence why I guessed [here](https://gitlab.com/davidbittner/raur/issues/5#note_209478920) this was to do with raur ext without seeing this issue.

Anyway I decided to go with an `Rc` instead seems as you don't really want to clone the package every time you want to keep it around. Especially since most fields are `Vec<String>` which is a ton of heap allocation.
